// Service worker for the hosted build. Generated by scripts/build.mjs, which
// fills in the asset list and a version from the files' contents. Everything
// the app needs is cached on install, so it opens offline. The app makes no
// other network requests.
//
// Updates wait for you (DESIGN.md §4.5). A new version installs in the background,
// then waits while an older one runs the page, so nothing changes under a recording.
// The page offers Reload (src/ui/UpdateBanner.tsx), which sends SKIP_WAITING. A first
// install has no older version to wait for, so it starts at once by itself.
const VERSION = '2f9465ff44f1';
const ASSETS = ["./apple-touch-icon.png","./assets/docxWrite-8EhLmP_0.js","./assets/index-Clrq56wU.js","./assets/logo-mark-JT7meKqO.png","./assets/pdf-DXLkaK0q.js","./assets/pdf.worker.min-CjEcRF4W.mjs","./assets/pdf.worker.min-DI4FfYVf.js","./assets/style-CRlWSExt.css","./assets/syncEngine-BhIQiyyF.js","./icon-192.png","./icon-512.png","./icon-64.png","./index.html","./manifest-me.webmanifest","./manifest.webmanifest","./"];
const CACHE = `behaviour-data-${VERSION}`;

// Every file of this version, as full addresses.
const OWN = new Set(ASSETS.map((a) => new URL(a, self.registration.scope).href));

/** Whether every file a page names on this site is one of this version's own, so it opens offline
 *  from this version's copies. A newer page, fetched while its version is still installing, is not. */
function fitsThisVersion(html, base) {
  for (const m of html.matchAll(/\s(?:src|href)=["']([^"']+)["']/g)) {
    const url = new URL(m[1], base);
    if (url.origin !== self.location.origin) continue;
    url.hash = '';
    url.search = '';
    if (!OWN.has(url.href)) return false;
  }
  return true;
}

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)));
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (req.mode === 'navigate') {
    // The app shell: try the network for a newer version, fall back to the cache.
    // Only a complete, successful page from this site becomes the offline copy: an
    // error page, a redirect, or a file opened in a tab (version.json, an icon) never does.
    // And only a page this version can open offline: a newer one waits for its own worker.
    event.respondWith(
      fetch(req)
        .then((res) => {
          const page = res.ok && res.type === 'basic' && (res.headers.get('content-type') || '').includes('text/html');
          if (page) {
            const keep = res
              .clone()
              .text()
              .then((html) => (fitsThisVersion(html, req.url) ? caches.open(CACHE).then((c) => c.put('./index.html', new Response(html, { headers: { 'Content-Type': 'text/html; charset=utf-8' } }))) : undefined))
              .catch(() => undefined);
            event.waitUntil(keep);
          }
          return res;
        })
        .catch(() => caches.match('./index.html')),
    );
    return;
  }
  event.respondWith(caches.match(req).then((hit) => hit || fetch(req)));
});
